### ISSUE TITLE
Can't find Quartz on macOS

### ISSUE THREAD

**Issue by michaelmariaott** [DominiqueMakowski/MuseBSL#2]
If I run MuseLSL2 view I get the following error:

```
/Users/mmm/Projects/pulse_[2024-04]/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/mmm/Projects/pulse_[2024-04]/venv/bin/MuseLSL2", line 33, in <module>
    sys.exit(load_entry_point('MuseLSL2==0.2', 'console_scripts', 'MuseLSL2')())
  File "/Users/mmm/Projects/pulse_[2024-04]/venv/lib/python3.9/site-packages/MuseLSL2/__main__.py", line 59, in main
    cli = CLI(args.command)
  File "/Users/mmm/Projects/pulse_[2024-04]/venv/lib/python3.9/site-packages/MuseLSL2/cli.py", line 9, in __init__
    getattr(self, command)()
  File "/Users/mmm/Projects/pulse_[2024-04]/venv/lib/python3.9/site-packages/MuseLSL2/cli.py", line 61, in view
    from .view import view
  File "/Users/mmm/Projects/pulse_[2024-04]/venv/lib/python3.9/site-packages/MuseLSL2/view.py", line 14, in <module>
    from vispy import app, gloo, visuals
  File "/Users/mmm/Projects/pulse_[2024-04]/venv/lib/python3.9/site-packages/vispy/__init__.py", line 27, in <module>
    from .util import config, set_log_level, keys, sys_info  # noqa
  File "/Users/mmm/Projects/pulse_[2024-04]/venv/lib/python3.9/site-packages/vispy/util/__init__.py", line 14, in <module>
    from . import fonts       # noqa
  File "/Users/mmm/Projects/pulse_[2024-04]/venv/lib/python3.9/site-packages/vispy/util/fonts/__init__.py", line 13, in <module>
    from ._triage import _load_glyph, list_fonts  # noqa, analysis:ignore
  File "/Users/mmm/Projects/pulse_[2024-04]/venv/lib/python3.9/site-packages/vispy/util/fonts/_triage.py", line 14, in <module>
    from ._quartz import _load_glyph, _list_fonts
  File "/Users/mmm/Projects/pulse_[2024-04]/venv/lib/python3.9/site-packages/vispy/util/fonts/_quartz.py", line 12, in <module>
    from ...ext.cocoapy import cf, ct, quartz, CFRange, CFSTR, CGGlyph, UniChar, \
  File "/Users/mmm/Projects/pulse_[2024-04]/venv/lib/python3.9/site-packages/vispy/ext/cocoapy.py", line 1288, in <module>
    quartz = cdll.LoadLibrary(util.find_library('quartz'))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 444, in LoadLibrary
    return self._dlltype(name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(Quartz.framework/Quartz, 0x0006): tried: 'Quartz.framework/Quartz' (no such file), '/System/Volumes/Preboot/Cryptexes/OSQuartz.framework/Quartz' (no such file), '/usr/lib/Quartz.framework/Quartz' (no such file, not in dyld cache), 'Quartz.framework/Quartz' (no such file)
```

**Comment by DominiqueMakowski** [comment]
It seems to be a Python dependency issue. I'd try updating your python version for > 3.9
